name: Jekyll site CI

on:
  push

jobs:
  jekyll:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    # use Github Action's
    - uses: actions/checkout@v1
      with:
          path: vendor/bundle
          key: ${{runner.os}}-gems-{{hashFiles('**/Gemfile.lock')}}
          restore-keys: |
            ${{runner.os}}-gems-
            
    # Standard        
    - uses: helaili/jekyll-action@2.0.3
      env:
        JEKYLL_PAT: ${{secrets.JEKYLL_PAT}}
